name: Generate Snake

on:
  schedule: # setiap 12 jam
    - cron: "0 */12 * * *"
  workflow_dispatch: # bisa dijalankan manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: habibdani
          outputs: dist/snake.svg

      - name: Push Snake Animation
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          message: "Generate snake animation"
          add: "dist/snake.svg"
