name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # jalan tiap 12 jam
  workflow_dispatch:          # bisa dijalankan manual juga

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # wajib biar ada history git

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: habibdani   # ganti sesuai username GitHub kamu
          outputs: dist/snake.svg

      - name: Push snake.svg to output branch
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/snake.svg"
          message: "Generate snake animation"
          new_branch: output
          push: origin output --force
